### ISSUE TITLE
Update to support latest NPoco 3.2

### ISSUE THREAD

**Issue by alafi** [izio/NPoco.Identity.Provider#1]
Would you please update your provider to support NPoco 3.2.
Currently extension method `BuildRelatedSelectQuery` is referencing the property `MemberInfo` on `PocoColumn` which had been renamed to `MemberInfoData`.
This issue is giving runtime errors.
Thank you.

**Comment by patrick-robin** [comment]
Thanks for the heads up, will fix it up shortly.

**Comment by patrick-robin** [comment]
Have got this working using the NPoco 3.2 package on nuget however getting it to work requires a primary key to be specified for the classes implementing `IIdentityRoles`and `IIdentityLogin` though I'm currently trying to figure out if there's a way around the issue and will publish an update soon.

**Comment by patrick-robin** [comment]
Fixed in v1.0.2 https://github.com/izio/NPoco.Identity.Provider/releases/tag/v1.0.2
